package org.pahappa.systems.requisitionapp.models.utils;

public enum Permission {
    // users
    VIEW_USERS, EDIT_USER, DELETE_USER, CREATE_USER, SEARCH_USERS,

    //roles
    CREATE_ROLE, DELETE_ROLE, EDIT_ROLE, VIEW_ROLES,

    // accountability
    CREATE_ACCOUNTABILITY, EDIT_ACCOUNTABILITY,

    // requisitions
    CREATE_REQUISITION, EDIT_REQUISITION, DELETE_REQUISITION, APPROVE_REQUISITION, REJECT_REQUISITION, VIEW_REQUISITIONS, VIEW_ALL_REQUISITIONS, REVIEW_REQUISITION,

    // budget lines
    CREATE_BUDGET_LINE, EDIT_BUDGET_LINE, DELETE_BUDGET_LINE, APPROVE_BUDGET_LINE, REJECT_BUDGET_LINE, VIEW_BUDGET_LINES,

    // budget line categories
    CREATE_BUDGET_LINE_CATEGORY, EDIT_BUDGET_LINE_CATEGORY, DELETE_BUDGET_LINE_CATEGORY, APPROVE_BUDGET_LINE_CATEGORY, REJECT_BUDGET_LINE_CATEGORY, VIEW_BUDGET_LINE_CATEGORY,

    DISBURSE_MONEY,

    VIEW_DASHBOARD, VIEW_SETTINGS

}
